---
title       : CRISP-Antisaccade
subtitle    : Early simulation analysis
author      : Ryan Hope
job         : CogWorks Lab, Rensselaer Polytechnic Institute
biglogo     : rpi_logo.png
logo        : cogworks_logo.png
framework   : io2012
highlighter : highlight.js
hitheme     : tomorrow
widgets     : [mathjax]
mode        : selfcontained
knit        : slidify::knit2slides
---

```{r,include=FALSE}
setwd("~/PyeMovements/")
require(ggplot2)
```

## Max Trials (N=11,timer=.250,labile=.180)
 
```{r, echo=FALSE}
data.trials = read.delim("sim_trials.dat",header=T)
ggplot(data.trials) + 
  geom_line(aes(x=latency,group=max_trials,color=max_trials),stat="density",size=1.25) +
  scale_color_continuous("Trials") + 
  theme_bw() +
  theme(legend.position = c(0.8, 0.8)) +
  xlab("Latency (in seconds) of first saccade post cue appearance") +
  ylab("Density") +
  coord_cartesian(xlim=c(0,1))
```

--- &twocol

## Mean Timer (N=11,labile=.180)

*** =left

```{r, echo=FALSE}
data.timer = read.delim("sim_timer.dat",header=T)
ggplot(data.timer) + 
  geom_line(aes(x=latency,group=timer_mean,color=timer_mean),stat="density",size=1.25) +
  scale_color_continuous("Mean Timer (s)") + 
  theme_bw() +
  theme(legend.position = c(0.8, 0.8)) +
  xlab("Latency (in seconds) of first saccade post cue appearance") +
  ylab("Density") +
  coord_cartesian(xlim=c(0,1))
```

*** =right

- The timer value seems to interact with the labile stage duration
 - When timer interval << labile duration, kurtosis <0, labile duration dominates mode
 - When timer interval ~= labile duration, kurtosis >0
 - When timer interval >> labile duration, kurtosis <0, timer interval dominates mode

---

## Mean Labile (N=11,timer=.250)

```{r, echo=FALSE}
data.labile = read.delim("sim_labile.dat",header=T)
ggplot(data.labile) + 
  geom_line(aes(x=latency,group=labile_mean,color=labile_mean),stat="density",size=1.25) +
  scale_color_continuous("Mean Labile (s)") + 
  theme_bw() +
  theme(legend.position = c(0.8, 0.8)) +
  xlab("Latency (in seconds) of first saccade post cue appearance") +
  ylab("Density") +
  coord_cartesian(xlim=c(0,1))
```

---

## Gap Cancellation (N=11,timer=.250,labile=.180)
 
```{r, echo=FALSE}
data.gap = read.delim("sim_gap.dat",header=T)
ggplot(data.gap) + 
  geom_line(aes(x=latency,group=gap_cancel_prob,color=gap_cancel_prob),stat="density",size=1.25) +
  scale_color_continuous("Gap Cancellation Probability") + 
  theme_bw() +
  theme(legend.position = c(0.8, 0.8)) +
  xlab("Latency (in seconds) of first saccade post cue appearance") +
  ylab("Density") +
  coord_cartesian(xlim=c(0,1))
```

---
 
## Cue Cancellation (N=11,timer=.250,labile=.180)
 
```{r, echo=FALSE}
data.cue = read.delim("sim_cue.dat",header=T)
ggplot(data.cue) + 
  geom_line(aes(x=latency,group=cue_cancel_prob,color=cue_cancel_prob),stat="density",size=1.25) +
  scale_color_continuous("Cue Cancellation Probability") + 
  theme_bw() +
  theme(legend.position = c(0.8, 0.8)) +
  xlab("Latency (in seconds) of first saccade post cue appearance") +
  ylab("Density") +
  coord_cartesian(xlim=c(0,1))
```
